CREATE DATABASE OceanPollution;
USE OceanPollution;

CREATE TABLE DATE_DIMENSION(
	DATE_ID	INTEGER	NOT NULL,
    MEASUREMENT_DATE DATE,
    MEASUREMENT_TIME TIME,
    MEASUREMENT_DAY	INT,
    MEASUREMENT_MONTH	INT,
    MEASUREMENT_YEAR	INT,
CONSTRAINT DATE_DIMENSION_PK Primary Key(DATE_ID));
  
CREATE TABLE TEMPERATURE_DIMENSION(
	TEMPERATURE_ID	INTEGER	NOT NULL,
    LICOR_TEMPERATURE DECIMAL (3,1),
    SEASURFACE_TEMPERATURE DECIMAL (4,2),
CONSTRAINT TEMPERATURE_DIMENSION_PK Primary Key(TEMPERATURE_ID));

CREATE TABLE LOCATION_DIMENSION(
	LOCATION_ID	INTEGER	NOT NULL,
    LATITUDE DECIMAL (3,2),
    LONGITUDE DECIMAL (5,2),
CONSTRAINT LOCATION_DIMENSION_PK Primary Key(LOCATION_ID));

CREATE TABLE PLASTIC_DIMENSION(
	PLASTIC_ID	INTEGER	NOT NULL,
    PLASTIC_TYPE VARCHAR (50),
    PLASTIC_SIZE VARCHAR (50),
    HARD_PLASTIC INT,
	PLASTIC_LINES INT,
    PLASTIC_PELLETS	INT,
    FOAMED_MATERIAL INT,
    PLASTIC_TOTAL INT,
CONSTRAINT PLASTIC_DIMENSION_PK Primary Key(PLASTIC_ID));

CREATE TABLE CARBONDIOXIDE_DIMENSION(
	CO2_ID	INTEGER	NOT NULL,
    CO2_SeaWaterWet  DECIMAL (4,1),
    CO2_AirWet DECIMAL (4,1),
    CO2_SeaWaterDry DECIMAL (4,1),
	CO2_AirDry  DECIMAL (4,1),
CONSTRAINT CARBONDIOXIDE_DIMENSION_PK Primary Key(CO2_ID));

CREATE TABLE SALINITY_DIMENSION(
	SALINITY_ID	INTEGER	NOT NULL,
    SALINITY DECIMAL (5,3),
CONSTRAINT SALINITY_DIMENSION_PK Primary Key(SALINITY_ID));

CREATE TABLE FACT_TABLE(
	DATE_ID	INTEGER	NOT NULL,
	TEMPERATURE_ID	INTEGER	NOT NULL,
    LOCATION_ID	INTEGER	NOT NULL,
    PLASTIC_ID	INTEGER	NOT NULL,
    CO2_ID	INTEGER	NOT NULL,
	SALINITY_ID	INTEGER	NOT NULL,
    QUALITY_CO2_DRY INT,
	QUALITY_CO2_WET INT,
CONSTRAINT Fact_Table_DATE_FK foreign key(DATE_ID) references DATE_DIMENSION(DATE_ID),
CONSTRAINT Fact_Table_TEMPERATURE_FK foreign key(TEMPERATURE_ID) references  TEMPERATURE_DIMENSION(TEMPERATURE_ID), 
CONSTRAINT Fact_Table_LOCATION_FK foreign key(LOCATION_ID) references LOCATION_DIMENSION(LOCATION_ID),
CONSTRAINT Fact_Table_PLASTIC_FK foreign key(PLASTIC_ID) references PLASTIC_DIMENSION(PLASTIC_ID),
CONSTRAINT Fact_Table_CO2_FK foreign key(CO2_ID) references  CARBONDIOXIDE_DIMENSION(CO2_ID), 
CONSTRAINT Fact_Table_SALINITY_FK foreign key(SALINITY_ID) references SALINITY_DIMENSION(SALINITY_ID));

SELECT * FROM DATE_DIMENSION;
SELECT * FROM SALINITY_DIMENSION;
SELECT * FROM TEMPERATURE_DIMENSION;
SELECT * FROM LOCATION_DIMENSION;
SELECT * FROM PLASTIC_DIMENSION;
SELECT * FROM CARBONDIOXIDE_DIMENSION;
SELECT * FROM SALINITY_DIMENSION;

SELECT * FROM FACT_TABLE;

## Question 1: How much CO2 is present in the atmosphere of the Pacific Ocean and 
## How much CO2 has dissoved in the sea water within the 7 years?

## CO2_AirDry of 2010
SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(CARBONDIOXIDE_DIMENSION.CO2_AirDry)
	FROM DATE_DIMENSION
    INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
    INNER JOIN CARBONDIOXIDE_DIMENSION ON FACT_TABLE.CO2_ID= CARBONDIOXIDE_DIMENSION.CO2_ID
		WHERE MEASUREMENT_YEAR=2010
			AND CO2_AirDry>0;
##Result - 2010: Carbon dioxide present in the atmosphere (CO2_AirDry) is 389.42 μmol/mol.          

## CO2_AirDry of 2017 
SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(CARBONDIOXIDE_DIMENSION.CO2_AirDry)
	FROM DATE_DIMENSION
    INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
    INNER JOIN CARBONDIOXIDE_DIMENSION ON FACT_TABLE.CO2_ID= CARBONDIOXIDE_DIMENSION.CO2_ID
		WHERE MEASUREMENT_YEAR=2017
			AND CO2_AirDry>0;
##Result - 2017: Carbon dioxide present in the atmosphere (CO2_AirDry) is 403. 72 μmol/mol.

##CO2_SeaWaterDry of 2010
SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(CARBONDIOXIDE_DIMENSION.CO2_SeaWaterDry)
	FROM DATE_DIMENSION
    INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
    INNER JOIN CARBONDIOXIDE_DIMENSION ON FACT_TABLE.CO2_ID= CARBONDIOXIDE_DIMENSION.CO2_ID
		WHERE MEASUREMENT_YEAR=2010
			AND CO2_SeaWaterDry>0;
##Result - 2010: Carbon dioxide dissolved in the sea water (CO2_SeaWaterDry) is 461.28 μmol/mol.

##CO2_SeaWaterDry of 2017           
SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(CARBONDIOXIDE_DIMENSION.CO2_SeaWaterDry)
	FROM DATE_DIMENSION
    INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
    INNER JOIN CARBONDIOXIDE_DIMENSION ON FACT_TABLE.CO2_ID= CARBONDIOXIDE_DIMENSION.CO2_ID
		WHERE MEASUREMENT_YEAR=2017
			AND CO2_SeaWaterDry>0;
##Result - 2017: Carbon dioxide dissolved in the sea water (CO2_SeaWaterDry) is 441.99 μmol/mol.
				
 ## Question 2: Has the salinity of Pacific Ocean changed throughout the years?
 ## What was the average salinity each year? 
 
 ## Year: 2010
 SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(SALINITY_DIMENSION.SALINITY) as Average_salinity2010
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN SALINITY_DIMENSION ON FACT_TABLE.SALINITY_ID= SALINITY_DIMENSION.SALINITY_ID
				WHERE SALINITY>0 
                AND MEASUREMENT_YEAR=2010;
  ## Year: 2011               
 SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(SALINITY_DIMENSION.SALINITY) as Average_salinity2011
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN SALINITY_DIMENSION ON FACT_TABLE.SALINITY_ID= SALINITY_DIMENSION.SALINITY_ID
				WHERE SALINITY>0 
                AND MEASUREMENT_YEAR=2011;
		
 ## Year: 2012               
 SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(SALINITY_DIMENSION.SALINITY) as Average_salinity2012
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN SALINITY_DIMENSION ON FACT_TABLE.SALINITY_ID= SALINITY_DIMENSION.SALINITY_ID
				WHERE SALINITY>0 
                AND MEASUREMENT_YEAR=2012;
                
## Year: 2013              
 SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(SALINITY_DIMENSION.SALINITY) as Average_salinity2013
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN SALINITY_DIMENSION ON FACT_TABLE.SALINITY_ID= SALINITY_DIMENSION.SALINITY_ID
				WHERE SALINITY>0 
                AND MEASUREMENT_YEAR=2013;   

 ## Year: 2014              
 SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(SALINITY_DIMENSION.SALINITY) as Average_salinity2014
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN SALINITY_DIMENSION ON FACT_TABLE.SALINITY_ID= SALINITY_DIMENSION.SALINITY_ID
				WHERE SALINITY>0 
                AND MEASUREMENT_YEAR=2014;

 ## Year: 2015               
 SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(SALINITY_DIMENSION.SALINITY) as Average_salinity2015
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN SALINITY_DIMENSION ON FACT_TABLE.SALINITY_ID= SALINITY_DIMENSION.SALINITY_ID
				WHERE SALINITY>0 
                AND MEASUREMENT_YEAR=2015;

 ## Year: 2016              
 SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(SALINITY_DIMENSION.SALINITY) as Average_salinity2016
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN SALINITY_DIMENSION ON FACT_TABLE.SALINITY_ID= SALINITY_DIMENSION.SALINITY_ID
				WHERE SALINITY>0 
                AND MEASUREMENT_YEAR=2016;

 ## Year: 2017              
 SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(SALINITY_DIMENSION.SALINITY) as Average_salinity2017
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN SALINITY_DIMENSION ON FACT_TABLE.SALINITY_ID= SALINITY_DIMENSION.SALINITY_ID
				WHERE SALINITY>0 
                AND MEASUREMENT_YEAR=2017;

##Result : The average of salinity in 2010, 2011, 2014, 2015, 2016, and 2017 
##                           was 35.18, 35.41, 34.22, 34.37, 35.09, and 34.73, ppm respectively.
## The COUNT () function was used to return the number of rows, however, 
## In 2012 and 2013 the numbers of rows returned were 0. 
## Therefore, it shows that there was no data collected for salinity in 2012 and 2013.

 ## Year: 2012               
 SELECT DATE_DIMENSION.MEASUREMENT_YEAR, COUNT(SALINITY_DIMENSION.SALINITY) 
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN SALINITY_DIMENSION ON FACT_TABLE.SALINITY_ID= SALINITY_DIMENSION.SALINITY_ID
				WHERE SALINITY>0 
                AND MEASUREMENT_YEAR=2012;
                
## Year: 2013              
 SELECT DATE_DIMENSION.MEASUREMENT_YEAR, COUNT(SALINITY_DIMENSION.SALINITY) 
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN SALINITY_DIMENSION ON FACT_TABLE.SALINITY_ID= SALINITY_DIMENSION.SALINITY_ID
				WHERE SALINITY>0 
                AND MEASUREMENT_YEAR=2013; 

## Question 3: Salinity of ocean water is also related to the temperature regulation. 
## Is there any correlation between salinity and temperature? 
## If so, by how much has the temperature increased?

## Year: 2011					
  SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(SALINITY_DIMENSION.SALINITY), AVG(TEMPERATURE_DIMENSION.SEASURFACE_TEMPERATURE)
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN SALINITY_DIMENSION ON FACT_TABLE.SALINITY_ID= SALINITY_DIMENSION.SALINITY_ID
            INNER JOIN TEMPERATURE_DIMENSION ON FACT_TABLE.TEMPERATURE_ID=TEMPERATURE_DIMENSION.TEMPERATURE_ID
				WHERE  SALINITY>0 
                AND MEASUREMENT_YEAR=2011;		
                
 ## Year: 2014
 SELECT DATE_DIMENSION.MEASUREMENT_YEAR, AVG(SALINITY_DIMENSION.SALINITY), AVG(TEMPERATURE_DIMENSION.SEASURFACE_TEMPERATURE)
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN SALINITY_DIMENSION ON FACT_TABLE.SALINITY_ID= SALINITY_DIMENSION.SALINITY_ID
            INNER JOIN TEMPERATURE_DIMENSION ON FACT_TABLE.TEMPERATURE_ID=TEMPERATURE_DIMENSION.TEMPERATURE_ID
				WHERE  SALINITY>0 
                AND MEASUREMENT_YEAR=2014;	
                
## Results: 
## In 2011, there is a decrease in temperature whereas increase in the salinity.
## In 2014, there is an increase in the temperature and decrease in the salinity. 
## Therefore, the correlation between salinity and temperature seems to be inversely proportional.
## Yes, there is an increase in the sea surface temperature from 28.56°C to 30.16°C from 2010 to 2017.
## The highest temperature on is 30.77°C in 2014.

## Question 4. The El Nino phenomenon is mostly common around December. 
## Was it really warm in December compared to the other months of the year? 
## If it happens, what was the temperature in December compared to other months?

## Answer: To compare the El Nino Phenomenon the year used was 2014, 2015, and 2016. 
## The other years did not have temperature taken on December. 
## Different month from different year was randomly chosen and compared on the December of each year. 
 
## SEA SURFACE TEMPERATURE ON DECEMBER 2014
 SELECT DATE_DIMENSION.MEASUREMENT_MONTH, DATE_DIMENSION.MEASUREMENT_YEAR, AVG(TEMPERATURE_DIMENSION.SEASURFACE_TEMPERATURE)
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN TEMPERATURE_DIMENSION ON FACT_TABLE.TEMPERATURE_ID=TEMPERATURE_DIMENSION.TEMPERATURE_ID
				WHERE  MEASUREMENT_MONTH=12
                AND MEASUREMENT_YEAR=2014;
                
## SEA SURFACE TEMPERATURE ON OCTOBER 2014
 SELECT DATE_DIMENSION.MEASUREMENT_MONTH, DATE_DIMENSION.MEASUREMENT_YEAR, AVG(TEMPERATURE_DIMENSION.SEASURFACE_TEMPERATURE)
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN TEMPERATURE_DIMENSION ON FACT_TABLE.TEMPERATURE_ID=TEMPERATURE_DIMENSION.TEMPERATURE_ID
				WHERE  MEASUREMENT_MONTH=10
                AND MEASUREMENT_YEAR=2014;     

## SEA SURFACE TEMPERATURE ON DECEMBER 2015
SELECT DATE_DIMENSION.MEASUREMENT_MONTH, DATE_DIMENSION.MEASUREMENT_YEAR, AVG(TEMPERATURE_DIMENSION.SEASURFACE_TEMPERATURE)
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN TEMPERATURE_DIMENSION ON FACT_TABLE.TEMPERATURE_ID=TEMPERATURE_DIMENSION.TEMPERATURE_ID
				WHERE  MEASUREMENT_MONTH=12
                AND MEASUREMENT_YEAR=2015; 

## SEA SURFACE TEMPERATURE ON SEPTEMBER 2015
SELECT DATE_DIMENSION.MEASUREMENT_MONTH, DATE_DIMENSION.MEASUREMENT_YEAR, AVG(TEMPERATURE_DIMENSION.SEASURFACE_TEMPERATURE)
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN TEMPERATURE_DIMENSION ON FACT_TABLE.TEMPERATURE_ID=TEMPERATURE_DIMENSION.TEMPERATURE_ID
				WHERE  MEASUREMENT_MONTH=9
                AND MEASUREMENT_YEAR=2015;
                
## SEA SURFACE TEMPERATURE ON DECEMBER 2016
SELECT DATE_DIMENSION.MEASUREMENT_MONTH, DATE_DIMENSION.MEASUREMENT_YEAR, AVG(TEMPERATURE_DIMENSION.SEASURFACE_TEMPERATURE)
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN TEMPERATURE_DIMENSION ON FACT_TABLE.TEMPERATURE_ID=TEMPERATURE_DIMENSION.TEMPERATURE_ID
				WHERE  MEASUREMENT_MONTH=12
                AND MEASUREMENT_YEAR=2016;

## SEA SURFACE TEMPERATURE ON AUGUST 2016
SELECT DATE_DIMENSION.MEASUREMENT_MONTH, DATE_DIMENSION.MEASUREMENT_YEAR, AVG(TEMPERATURE_DIMENSION.SEASURFACE_TEMPERATURE)
		FROM   DATE_DIMENSION
			INNER JOIN FACT_TABLE ON FACT_TABLE.DATE_ID= DATE_DIMENSION.DATE_ID
            INNER JOIN TEMPERATURE_DIMENSION ON FACT_TABLE.TEMPERATURE_ID=TEMPERATURE_DIMENSION.TEMPERATURE_ID
				WHERE  MEASUREMENT_MONTH=8
                AND MEASUREMENT_YEAR=2016;

## Results : The temperature of the sea surface in the December in 2015 was 30.24°C and 2016 was 30.04°C 
## which are higher than the September of 2015 which was 29.26°C and August of 2016 was 29.82 °C. 
## The sea surface temperature of the October 2014 was 30.70°C and December of 2014 was 30.70°C. 
## Therefore, the sea surface temperature did rise in the month of December and is warmer than the other months of the year.